apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: url-shortener
  namespace: argocd
spec:
  description: URL shortener platform
  sourceRepos:
    - https://github.com/your-username/cloud-native-url-shortener.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: url-shortener
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
